- name: Instalar los paquetes necesarios para que apt funcione sobre HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: A침adir la clave de firma de paquetes de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: A침adir el repositorio apt para la versi칩n estable
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ UBUNTU_RELEASE }} stable
    state: present

- name: Instalar Docker y sus dependencias
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Arrancar el servicio Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Borrar el fichero de configuraci칩n de containerd
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Reiniciar containerd
  service:
    name: containerd
    daemon_reload: yes
    state: restarted
